### ISSUE TITLE
How to Serialize the values changed in a class not in __init__

### ISSUE THREAD

**Issue by DanteLuo** [rll/rllab#198]
I want to create a AntEnv modified version which can store a goal and change the goal as I want so I have a class:
```python
class AntEnvMod(AntEnv, Serializable):
    def __init__(self, seed=42, *args, **kwargs):
        self.seed = seed
        super(AntEnvMod, self).__init__(*args, **kwargs)
        Serializable.quick_init(self, locals())

    def set_seed(self, seed):
        self.seed = seed
```

And then:
```python
env = AntEnvMod(seed=55)
print(env.seed)
print([pickle.loads(pickle.dumps(env)).seed for _ in range(10)])
env.set_seed(66)
print(env.seed)
print([pickle.loads(pickle.dumps(env)).seed for _ in range(10)])
```

I want to store the env with seed of 66 in pickle, how should I do that?

Thanks so much!

**Comment by ryanjulian** [comment]
Can you provide the output of your test program?

**Comment by DanteLuo** [comment]
The output is just use the default settings for the AntEnvMod and discards the changes I made in the env of the pickle.dumps().

**Comment by DanteLuo** [comment]
@ryanjulian The output is just use the default settings for the AntEnvMod and discards the changes I made in the env of the pickle.dumps().

**Comment by ryanjulian** [comment]
If you would like your seed to be serialized, you should include it as a constructor argument.

reference: https://github.com/rll/rllab/blob/master/rllab/core/serializable.py

Our `Serializable` implementation only serializes the constructor arguments (`args` and `kwargs`) and assumes an object can be cloned by reconstructing a new instance of the serialized class using those arguments. It does not track mutations after object construction.

I realize that this is not the most general way of serializing, but it is sufficient for rllab, and an important assumption for other parts of how the program functions (e.g. many times objects are cloned across process or network boundaries by serializing their constructor arguments and making new objects on the other side of that boundary. Many objects in rllab would be very difficult to serialize in general without this assumption, because they rely on very large internal state, produced by software outside of our control (e.g. TensorFlow computation graphs).

**Comment by DanteLuo** [comment]
Thanks! It works fine now!
